<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 *
 * @package    core
 * @subpackage admin
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['accounts'] = 'Nutzer*innenkonten';
$string['adminseesall'] = 'Administrator*innen sehen alles';
$string['adminseesallevents'] = 'Administrator*innen sehen alle Termine';
$string['adminseesownevents'] = 'Administrator*innen sehen nur eigene Termine';
$string['ageofdigitalconsentmap_desc'] = 'Das Alters, ab dem Nutzer\\*innen selber ihre Zustimmung zur Verarbeitung von Daten geben dürfen, ist gesetzlich festgelegt. Geben Sie jedes Alter in einer neuen Zeile mit folgendem Format ein: Ländercode, Alter (getrennt durch ein Komma). Das Standardalter wird durch \\* anstelle des Ländercodes angezeigt. Ländercodes entsprechen der Norm ISO 3166-2.';
$string['allowuserswitchrolestheycantassign'] = 'Rollenwechsel für Nutzer*innen erlauben, die kein Recht zur Rollenzuweisung besitzen';
$string['allowuserthemes'] = 'Designwechsel für Nutzer*innen erlauben';
$string['alternativefullnameformat_desc'] = 'Legen Sie hier fest, wie Namen für Nutzer\\*innen angezeigt werden, die über die Berechtigung \'viewfullname\' verfügen. Dies sind normalerweise: Manager\\*innen, Trainer\\*innen sowie Trainer\\*innen ohne Bearbeitungsrecht. Es können die gleichen Platzhalter verwendet werden wie für die Einstellungen zum \'Vollständigen Namen\'.';
$string['authpreventaccountcreation_help'] = 'Wenn sich ein\\*e Nutzer\\*in authentifiziert, wird auf der Website automatisch ein Nutzendenkonto angelegt, wenn dieses noch nicht existiert. Diese Option sollte aktiviert werden, wenn eine externe Datenbank wie z.B. LDAP zur Authentifizierung genutzt wird und sich nur bereits existierende Nutzer\\*innen authentifizieren sollen. Neue Nutzendenkonten müssen dann von Hand oder Nutzendenupload per cvs angelegt werden. Hinweis: diese Einstellung gilt nicht für die MNet-Authentifizierung.';
$string['cacheapplicationhelp'] = 'Elemente im Cache gelten für alle Nutzer*innen und verfallen erst nach einer gewissen Zeit';
$string['cachejs_help'] = 'Bei Javascript führen Komprimierung und Caching zu höherer Leistung. Diese Option sollte für Produktivsysteme unbedingt aktiviert sein. Entwickler\\*innen möchten die Option eventuell deaktivieren.';
$string['cachetemplates_help'] = 'Das Template-Caching verbessert das Ladeverhalten und ist für produktive Seite dringlich empfohlen. Entwickler\\*innen werden es ggfs. deaktivieren.';
$string['calendartype_desc'] = 'Wählen Sie einen Kalendertyp für die gesamte Website. Diese Einstellung kann in den Kurseinstellungen oder in den persönlichen Nutzendenprofilen geändert werden.';
$string['configallcountrycodes'] = 'Diese Länderliste wird an unterschiedlichen Stellen benutzt, z.B. im Nutzer*innenprofil. Falls das Feld leer bleibt, wird die gesamte Liste aus der Datei countries.php im englischen Sprachpaket benutzt. Dies ist die Liste gemäß ISO 3166-1. Über eine kommagetrennte Liste können Sie die Auswahlmöglichkeiten einschränken, z.B. \'GB,FR,ES\'. Falls Sie weitere Codes ergänzen möchten, so müssen Sie diese Codes in der Datei countries.php in Ihrem Sprachpaket hinzufügen.';
$string['configallowassign'] = 'Die linksseitig genannten Rolleninhaber dürfen alle rechts in den Spalten markierten Rollen an andere Nutzer*innen zuweisen.';
$string['configallowblockstodock'] = 'Diese Option legt fest, ob Nutzer*innen die Blöcke in ein spezielles Dock ablegen können, wobei nicht alle Designs diese Möglichkeit unterstützen.';
$string['configallowcohortthemes'] = 'Die Funktion ermöglicht es, einer globalen Gruppe ein Design zuzuweisen. Dies betrifft dann alle Nutzer*innen, die genau einer einzelnen globalen Gruppe zugeordnet sind oder wenn alle globalen Gruppen das gleiche Design verwenden.';
$string['configallowcoursethemes'] = 'Mit der Aktivierung erlauben Sie die Auswahl kursspezifischer Designs. Ein Kursdesign hat Vorrang vor allen anderen Designfestlegungen (Website, Kursbereich, Nutzer*in, globale Gruppe oder URL-definierte Designs).';
$string['configallowemojipicker'] = 'Mit der Emoji-Auswahl in den Atto-Werkzeugen können Nutzer*innen Emojis (z.B. Smilies oder Symbolbilder) auswählen und in Mitteilungen hinzufügen.';
$string['configallowobjectembed'] = 'Aus Sicherheitsgründen dürfen normale Nutzer*innen keine Multmedia-Objekte über die HTML-Tags &lt;embed&gt; und &lt;object&gt; in den HTML-Code einbinden. Multimedia-Objekte sind alternativ auch über den Mediafilter nutzbar, ohne dabei Sicherheitsprobleme zu verursachen. Wenn Sie die HTML-Tags für alle erlauben möchten, aktivieren Sie diese Option.';
$string['configallowoverride2'] = 'Wählen Sie, welche Rollen durch eine Rolle aus der linken Spalte verändert werden dürfen. <br />Beachten Sie dabei, dass diese Einstellungen ausschließlich für Nutzer*innen gelten, für die die Rechte moodle/role:override oder moodle/role:safeoverride gesetzt sind.';
$string['configallowuserblockhiding'] = 'Möchten Sie das Minimieren von Blöcken erlauben? Die Blöcke werden dabei bis auf die Kopfzeile reduziert. Jede Person beeinflusst ausschließlich ihre eigene Nutzer*innenansicht.';
$string['configallowusermailcharset'] = 'Diese Option legt fest, ob Nutzer*innen den E-Mail-Zeichensatz in ihren persönlichen Einstellungen selber festlegen können.';
$string['configallowuserthemes'] = 'Die Einstellung erlaubt allen Nutzer*innen, ein eigenes Design auszuwählen. Damit wird das Design der Website überschrieben, aber keine kursspezifische Design-Vorgabe.';
$string['configallowview'] = 'Wählen Sie aus, welche Rollen für Nutzer*innen sichtbar sein sollen, wenn sie bereits eine Rolle haben.';
$string['configallusersaresitestudents'] = 'Mit dieser Option legen Sie den Zugriff zu den Lernaktivitäten auf der Startseite fest. Wenn Sie \'Ja\' auswählen, können alle eingetragenen Nutzer*innen die Lernaktivitäten auf der Startseite durchführen. Wenn Sie \'Nein\' auswählen, können nur diejenigen, die derzeit in mindestens einem Kurs eingetragen sind, die Lernaktivitäten auf der Startseite ausführen. Nur Administrator*innen und speziell zugelassene Trainer*innen dürfen die Aktivitäten auf der Startseite einrichten und bearbeiten.';
$string['configauthenticationplugins'] = 'Wählen Sie die Authentifizierungsverfahren aus, die Sie benutzen möchten, und ordnen Sie diese in eine Reihenfolge der Nutzung.</br> <b>Hinweis:</b> Bei einer späteren Deaktivierung von Authentifizierungsverfahren kann es passieren, dass Nutzer*innen mit dem deaktivierten Verfahren keinen Zugang mehr erhalten. Prüfen Sie dies sorgfältig.</br>';
$string['configautolang'] = 'Leitet die Standardsprache von den Browsereinstellungen des\\*der Nutzers\\*in ab. Wenn die Funktion deaktiviert ist wird die Default-Einstellung für die Sprache der Moodle-Installation verwendet.';
$string['configcountry'] = 'Diese Option legt das Land fest, das als Vorgabe für neue Nutzer*innenkonten eingetragen ist. Wenn Nutzer*innen ihr Land selber eintragen sollen, lassen Sie das Feld leer.';
$string['configcourserequestnotify2'] = 'Nutzer*innen, die benachrichtigt werden sollen, wenn ein Kurs angefordert wird. Es werden nur Nutzer*innen gelistet, die eine Kursanfrage annehmen dürfen.';
$string['configcustomusermenuitems'] = 'Sie können den Inhalt des Nutzer*innenmenüs konfigurieren (mit Ausnahme des Logout-Links, der automatisch hinzugefügt wird). Jede Menüzeile wird durch das Zeichen | getrennt und besteht aus 1.) einem Text oder der Angabe "langstringname, componentname" oder reinem Text, 2.) einer URL und 3.) einem Icon als pix-Symbol (im Verzeichnis /pix oder mit der Struktur [Unterverzeichnisname]/[Iconname) oder als URL. Trennungen können durch Eingabe einer Linie oder einem oder mehreren #-Zeichen eingegeben werden.';
$string['configdbsessions'] = 'Bei der Aktivierung dieser Einstellung wird die Datenbank verwendet, um Informationen über aktuelle Sessions abzuspeichern. Das ist sinnvoll bei sehr großen Anwendungen oder Anwendungen, die über mehrere Cluster von Servern verteilt arbeiten. Meist kann die Einstellung deaktiviert bleiben. Bei einer Einstellungsänderung werden alle aktuellen Nutzer*innen ausgeloggt (auch die Administrator*innen). Falls Sie MySQL benutzen, stellen Sie sicher, dass \'max_allowed_packet\' in der Datei my.cnf (oder my.ini) mindestens 4M ist. Andere Treiber für Sessions können direkt in der config.php angepasst werden. Vorlagen finden Sie dazu in der config-dist.php-Datei. Diese Option wird nicht mehr angezeigt wenn Einstellungen in der config.php vorgenommen wurden.';
$string['configdebug'] = 'Wenn Sie diese Funktion einschalten, werden die Fehlermeldungen von PHP erweitert, so dass mehr Warnungen ausgegeben werden. Dies ist nur für Entwickler*innen nützlich.';
$string['configdebugvalidators'] = 'Aktivieren Sie diese Option, um Links zu externen Validierungsservern in der Fußzeile anzuzeigen. Möglicherweise müssen Sie einen neue*n Nutzer*in mit dem Anmeldenamen <em>w3cvalidator</em> erstellen und den Gastzugang freischalten. Diese Änderungen erlauben unauthorisierte Serverzugriffe und sollten nicht auf Produktivsystemen eingeschaltet werden!';
$string['configdefaulthomepage'] = 'Diese Option legt fest, welche Seite eingeloggte Nutzer*innen in der Startseite als ersten Link sehen.';
$string['configdefaultrequestcategory'] = 'Kurse, die von Nutzer*innen mit dem Recht, neue Kurse im Systemkontext anzufordern, werden in diese Kategorie eingeordnet, falls Nutzer*innen keinen anderen Kursbereich auswählen oder auswählen können. Beantragte Kurse werden automatisch in diesem Kursbereich angelegt, falls kein anderer Kursbereich angegeben wurde.';
$string['configdefaultuserroleid'] = 'Angemeldete Nutzer\\*innen erhalten für die gesamte Website automatisch die hier angegebene Rolle zugewiesen, u.z. zusätzlich zu anderen Rollenzuweisungen. Dafür ist vorerst die Rolle "Authentifizierte\\*r Nutzer`\\*in" eingestellt. Achten Sie darauf, dass Sie mit Ihrer Einstellung keine Konflikte mit anderen Rollen schaffen und dass die Nutzer\\*innen sinnvolle Dinge tun können, z.B. ihr Nutzendenprofil verwalten, den eigenen Kalender verwalten oder Blogeinträge schreiben.';
$string['configdeleteincompleteusers'] = 'Nach dieser Zeit werden alle Nutzer*innenkonten gelöscht, bei denen der Vorname, der Nachname oder die E-Mail-Adresse fehlt.';
$string['configdeleteunconfirmed'] = 'Bei bestimmten Authentifizierungsmethoden, wie etwa der E-Mail-basierten Selbstregistrierung, müssen Nutzer*innen ihr Konto innerhalb einer bestimmten Zeit bestätigen. Nach dieser Zeit werden alle alten unbestätigten Konten gelöscht.';
$string['configdisableuserimages'] = 'Nutzer*innen verbieten, ihre Profilbilder ändern zu können.';
$string['configemailchangeconfirmation'] = 'Wenn Nutzer*innen in ihrem Profil die E-Mail-Adresse ändern, dann ist eine E-Mail-Bestätigung notwendig';
$string['configemailfromvia'] = 'Via-Information in den Absender für ausgehende E-Mails einfügen. Der*die Empfänger*in wird damit informiert, von welcher Website die E-Mail gesendet wurde. Dies soll helfen, eine versehentliche Antwort an die Nicht-Antworten-Adresse zu verhindern.';
$string['configenableanalytics'] = 'Analytics-Modelle, z.B. "Teilnehmer*innen, bei denen das Risiko eines Schulabbruchs besteht" oder "Bevorstehende Aktivitäten", können Vorhersagen erstellen, Erkenntnisbenachrichtigungen senden und weitere Aktionen anbieten, z.B. Nutzer*innenmitteilungen versenden.';
$string['configenableblogs'] = 'Diese Option aktiviert für alle Nutzer*innen einen eigenen Blog.';
$string['configenablecourserequests'] = 'Wenn diese Option aktiviert ist, können Nutzer*innen mit dem Recht (moodle/course:request) neue Kurse anfordern. Diese Funktion ist für keine der Standardrollen zulässig und kann im System- oder Kategoriekontext angewendet werden.';
$string['configenabletrusttext'] = 'Standardmäßig bereinigt Moodle alle Texte, die von Nutzer*innen eingegeben werden. Dabei werden möglicherweise fehlerhafte Skripte oder Medien entfernt, die ein Sicherheitsrisiko darstellen könnten. Das Trusted Content-System bietet Nutzer*innen, denen Sie besonders vertrauen, erweiterte Inhalte auch ohne Filterung in den Beiträgen zu verwenden. Um dieses System zu aktivieren, müssen Sie zuerst diese Einstellung aktivieren und anschließend einer bestimmten Rolle das Trusted-Content-Recht erlauben. Texte, die von den betreffenden Nutzer*innen geschrieben oder hochgeladen werden, sind als vertrauenswürdig markiert und werden vor der Anzeige nicht bereinigt.';
$string['configenablewsdocumentation'] = 'Aktiviert die automatische Erstellung einer Dokumentation zu den Webservices. Nutzer*innen können auf ihre eigene Dokumentation für die Sicherheitsschlüssel über \'{$a}\' zugreifen. Es wird ausschließlich die Dokumentation für die aktivierten Protokolle angezeigt.';
$string['configforceloginforprofiles'] = 'Diese Option legt fest, dass Nutzer*innenprofile ausschließlich für angemeldete Personen sichtbar sind, nicht für Gäste oder Suchmaschinen. Wenn Sie die Option ausschalten, sind die Nutzer*innenprofile und deren Inhalte weltweit abrufbar und könnten zur Veröffentlichung von anstößigen Inhalten oder Werbung (Spam) missbraucht werden.';
$string['configfrontpageloggedin'] = 'Die ausgewählten Elemente werden auf der Startseite angezeigt, wenn Nutzer*innen angemeldet sind.';
$string['configgradebookroles'] = 'Diese Einstellung erlaubt Ihnen die Kontrolle, wer in den Bewertungen erscheint. Teilnehmer*innen müssen zuerst eine der Rollen in einem Kurs einnehmen, bevor sie in den Bewertungen dieses Kurses angezeigt werden.';
$string['confighiddenuserfields'] = 'Markieren Sie die Felder, deren Inhalte vor anderen Nutzer\\*innen, nicht aber vor Trainer\\*innen und Administrator\\*innen verborgen werden sollen. Dies erhöht den Datenschutz. Mit gedrückter strg/cmd-Taste können Sie auch mehrere Felder markieren.';
$string['configidnumber'] = 'Diese Option legt fest, ob (a) nicht nach einer ID-Nummer gefragt wird, (b) zwar nach einer ID-Nummer gefragt wird, aber das Feld leer bleiben kann oder (c) nach einer zwingenden Eingabe einer ID-Nummer gefragt wird. Eine eingegebene ID-Nummer wird im Nutzer*innenprofil angezeigt.';
$string['configintroadmin'] = 'Sie müssen eine*n Hauptadministrator*in einrichten, der die vollständige Kontrolle über die Website hat. Achten Sie darauf, unbedingt einen sicheren Anmeldenamen, ein sicheres Kennwort sowie eine gültige E-Mail-Adresse anzugeben. Weitere Administrator*innen können Sie später festlegen.';
$string['configlangmenu'] = 'Diese Option legt fest, ob Sie das Sprachmenü auf der Startseite und auf der Anmeldeseiten anzeigen möchten. Dies schränkt die Möglichkeit nicht ein, dass alle Nutzer*innen ihre bevorzugte Sprache im Nutzer*innenprofil einstellen können.';
$string['configloglifetime'] = 'Die angegebene Zeitdauer gibt an, für welchen Zeitraum die Logdaten der Nutzer*innenaktivitäten gespeichert werden. Ältere Logdaten werden automatisch gelöscht. Speichern Sie die Logdaten nur so lange, wie sie unbedingt benötigt werden. Wenn Sie bei Ihrem Server Leistungseinbrüche feststellen, sollten Sie den Zeitraum reduzieren. Werte kleiner als 30 werden nicht empfohlen, weil dann die Statistiken nicht mehr richtig arbeiten können.';
$string['configmaxusersperpage'] = 'Maximale Anzahl von Personen, die bei der Nutzer*innenauswahl in Kursen, Gruppen oder Webservices angezeigt werden.';
$string['configmessaging'] = 'Diese Option aktiviert das Mitteilungssystem systemweit für alle Nutzer*innen.';
$string['configmessagingallowemailoverride'] = 'Nutzer*innen erlauben, sich Systemnachrichten an andere E-Mail-Adressen senden zu lassen als im Profil angegeben.';
$string['configmessagingallusers'] = 'Wenn diese Option aktiviert ist, können Nutzer*innen bei der Suche nach anderen Personen alle registrierten Personen im System sehen. Die Profileinstellungen ermöglichen dann, dass jede Person selber festlegen kann, ob sie von jeder anderen Person Mitteilungen empfangen möchte. Ist die Funktion deaktiviert, wird die Funktion auf Personen aus den eigenen Kursen beschränkt. Eine Person kann dann im Profil festlegen, ob er nur von den Kontakten oder jedem*r Kursteilnehmer*in Mitteilungen empfangen möchte.';
$string['configmessagingdefaultpressenter'] = 'Ob Senden mit Eingabetaste als Voreinstellung in den Nutzer*inneneinstellungen gesetzt ist.';
$string['configmodchooserdefault'] = 'Soll die Aktivitätenauswahl den Nutzer*innen als Standardeinstellung gezeigt werden?';
$string['confignavcourselimit'] = 'Die Zahl legt die Anzahl der Kurse fest, die Nutzer*innen maximal in der Navigation angezeigt werden.';
$string['confignavshowallcourses'] = 'Diese Einstellung legt fest, dass Nutzer*innen zusätzlich zu "Meine Kurse" (Liste von Kursen, in denen sie eingeschrieben sind) auch Kurse (Liste aller Kurse) in der Navigation sehen.';
$string['confignoreplyaddress'] = 'E-Mails werden manchmal auf Veranlassung einer Person gesendet, z.B. bei Forumsbeiträgen. Tragen Sie in dieses Feld eine E-Mail-Adresse ein, die immer dann eingesetzt wird, wenn niemand die persönliche E-Mail-Adresse sehen oder für Antworten benutzen soll. Diese Einstellung wird auch als (nur für die Übertragung relevanter und für den*die Empfänger*in im Normalfall unsichtbarer) "Envelope Sender" der E-Mail genutzt.';
$string['confignotifyloginfailures'] = 'Systemnachrichten zu Login-Fehlern können an ausgewählte Nutzer*innen gesendet werden. Dazu muss ein interner Logstore (z.B. Standard-Logstore) aktiviert sein.';
$string['confignotifyloginthreshold'] = 'Nach wie vielen erfolglosen Anmeldeversuchen hintereinander für ein Nutzer*innenkonto oder über eine IP-Adresse soll eine Systemnachricht gesendet werden?';
$string['confignotloggedinroleid'] = 'Nicht auf der Website eingeloggte Nutzer*innen werden behandelt, als ob sie diese Rolle hätten. Die Rolle \'Gast\' ist in der Regel brauchbar. Sie können aber auch neue Rollen erstellen, die mehr oder weniger Einschränkungen vornehmen. Viele Aktivitäten, z.B. Beiträge schreiben oder Tests durchführen, erfordern aber immer eine richtige Anmeldung.';
$string['configpasswordpolicy'] = 'Wenn diese Option aktiviert ist, werden Nutzer*innenkennwörter anhand der in den folgenden Einstellungen angegebenen Kennwortrichtlinie überprüft. Das Aktivieren der Kennwortrichtlinie wirkt sich erst dann auf vorhandene Benutzer*innen aus, wenn diese ihr Kennwort ändern möchten, ändern müssen oder die Einstellung "Kennwort bei Anmeldung prüfen" aktiviert ist.';
$string['configpasswordpolicycheckonlogin'] = 'Wenn diese Option aktiviert ist, werden Nutzer*innenkennwörter bei jeder Anmeldung anhand der Kennwortrichtlinie überprüft. Wenn die Überprüfung fehlschlägt, müssen Nutzer*innen ihr Kennwort ändern, bevor sie fortfahren können. Es ist hilfreich, diese Einstellung nach dem Aktualisieren der Kennwortrichtlinie zu aktivieren.';
$string['configprofileroles'] = 'Liste der Rollen, die in Nutzer*innenprofilen und auf der Teilnehmer*innenseite sichtbar sind';
$string['configprofilesforenrolledusersonly'] = 'Um eine unerwünschte Nutzung durch Spammer zu vermeiden, sind die Profilbeschreibungen von Nutzer*innen ohne vorhandene Kurseinschreibung gesperrt. Neue Nutzer*innen müssen sich in mindestens einem Kurs eingeschrieben haben, um eine Profilbeschreibung hinzufügen zu können.';
$string['configrecaptchapublickey'] = 'Der Code (Site Key) dient zur Anzeige des Recaptcha-Elements bei der Nutzer*innenregistrierung. Sie erhalten den Code unter <a target="_blank" href="https://www.google.com/recaptcha">Google reCAPTCHA</a>.';
$string['configrequestedstudentname'] = 'Begriff für Teilnehmer*in in beantragten Kursen';
$string['configrequestedstudentsname'] = 'Begriff für Teilnehmer*innen in beantragten Kursen';
$string['configrequestedteachername'] = 'Begriff für Trainer*in in beantragten Kursen';
$string['configrequestedteachersname'] = 'Begriff für Trainer*innen in beantragten Kursen';
$string['configreverseproxyignore'] = 'Wenn sich Ihr Server hinter mehreren Reverse-Proxys befindet, die an den X-Forwarded-For-Header angehängt werden, müssen Sie eine kommagetrennte Liste von IP-Adressen oder Subnetzen der zu ignorierenden Reverse-Proxys angeben. Nur so können Sie die richtige IP-Adresse von Nutzer*innen feststellen.';
$string['configsectionuser'] = 'Nutzer*in';
$string['configsecureforms'] = 'Moodle kann eine erhöhte Sicherheitsstufe für Daten aus Web-Formularen nutzen. Sofern dies eingeschaltet ist, wird die Variable HTTP_REFERER gegen die Adresse des aktuellen Formulars geprüft. In einigen wenigen Fällen kann das Probleme verursachen, wenn der*die Nutzer*in eine Firewall benutzt (z.B. Zonealarm), die so konfiguriert ist, dass der HTTP_REFERER nicht mitgesendet wird. Das Ergebnis ist, dass Sie bei einem Formular nicht weiterkommen. Sofern Nutzer*innen z.B. Probleme mit der Zugangsseite haben, sollten Sie diese Einstellung deaktivieren - allerdings ist Ihre Seite so offener für Brute-Force-Attacken. Im Zweifelsfall belassen Sie es bei \'Ja\'.';
$string['configsessiontimeout'] = 'Wenn angemeldete Nutzer*innen länger keine Aktionen ausführen (z.B. keine Seiten laden), werden sie automatisch abgemeldet. Diese Variable legt die betreffende Zeitspanne fest.';
$string['configshowsiteparticipantslist'] = 'Alle Teilnehmer*innen und Trainer*innen der Website werden in der Nutzer*innengesamtliste geführt. Wer soll diese Liste sehen dürfen?';
$string['configstatsuserthreshold'] = 'Kurse mit einer geringeren Zahl von Nutzer*innen als in diesem Wert angegeben, werden beim Erstellen von Kursstatistiken nicht berücksichtigt.';
$string['configsupportemail'] = 'Diese E-Mail-Adresse wird Nutzer*innen dieser Website per E-Mail gesendet, wenn Sie z.B. ein neues Kennwort anfordern oder selber einen Nutzer*innenzugang anlegen. Wenn das Feld leer bleibt, wird keine E-Mail-Adresse angeboten. Die E-Mail-Adresse wird auch als Absenderadresse dieser Benachrichtigungen benutzt. Fehlt hier der Eintrag, so wird die E-Mail-Adresse des*der primären Administrators*in verwendet.';
$string['configsupportname'] = 'Beim Versand von E-Mails an Nutzer*innen wird der hier eingetragene Name als Ansprechpartner*in für den Support genannt. Dies betrifft z.B. E-Mails beim Anlegen neuer Nutzer*innenaccounts oder dem Anfordern von neuen Kennwörtern.';
$string['configsupportpage'] = 'Tragen Sie hier die Adresse einer Webseite ein, auf der Ihre Nutzer*innen speziell von Ihnen bereitgestellte Hilfeinformationen finden. Geben Sie die Adresse mit einem http:// oder https:// ein. Die Adresse wird bspw. in E-Mails an Nutzer*innen beim Anlegen von Nutzer*innenzugängen oder dem Anfordern von neuen Kennwörtern angezeigt. Wenn Sie keinen Eintrag vornehmen, wird in den E-Mails nichts angezeigt.';
$string['configuseblogassociations'] = 'Soll es für Nutzer*innen möglich sein, ihre Blogeinträge über die Zuordnung an Kurse und Kursmodule zu organisieren?';
$string['configverifychangedemail'] = 'Diese Option aktiviert die Prüfung bei der Änderung von E-Mail-Adressen, ob sie von vorgegebenen oder zurückzuweisenden E-Mail- Domains stammen. Ist die Funktion deaktiviert, erfolgt die Prüfung nur bei der Neuanlage von Nutzer*innenkonten.';
$string['contextlockappliestoadmin'] = 'Einfrieren von Kontexten gilt für Administrator*innen';
$string['contextlockappliestoadmin_desc'] = 'Wenn diese Option deaktiviert ist, können Administrator\\*innen auch eingefrorene Kontexte ändern.';
$string['coursecontactduplicates_desc'] = 'Wenn die Funktion aktiv ist werden bei Nutzern\\*innen, die in den Kursen mehrere Rollen innehaben alle Rollen angezeigt, sofern sie als Kontakt ausgewiesen werden. Wenn Sie die Funktion nicht nutzen wird nur diejenige Rolle angezeigt, die in der Auflistung der Rollen an der ersten Stelle steht.';
$string['courserequestnotifyemail'] = 'Guten Tag, der*die Nutzer*in {$a->user} hat einen neuen Kurs unter {$a->link} angefordert. Ihr E-Learning-Team';
$string['creatornewroleid'] = 'Rolle für Kursersteller*in in neuen Kursen';
$string['creatornewroleid_help'] = 'Falls ein\\*e Nutzer\\*in nicht bereits das Recht besitzt, den neuen Kurs zu verwalten, wird die Person mit dieser Rolle automatisch in den Kurs eingeschrieben.';
$string['cronerrorclionly'] = 'Der Internetzugriff für diese Seite wurde deaktiviert.';
$string['customusermenuitems'] = 'Einträge im Nutzer*innenmenü';
$string['debugdeveloper'] = 'DEVELOPER: PHP-Mitteilungen für Entwickler*innen anzeigen';
$string['defaultcity_help'] = 'Wenn Sie in diesem Feld eine Stadt bzw. einen Ort eintragen, wird diese Eingabe als Voreinstellung beim Anlegen neuer Nutzendenkonten verwendet.';
$string['defaulthomepage'] = 'Startseite für Nutzer*innen';
$string['defaultuserroleid'] = 'Rolle für Nutzer*innen';
$string['deleteincompleteusers'] = 'Unvollständige Nutzer*innenkonten löschen';
$string['deleteunconfirmed'] = 'Unbestätigte Nutzer*innenkonten löschen';
$string['deleteuser'] = 'Nutzer*innenkonto löschen';
$string['disableuserimages'] = 'Nutzer*innenbilder deaktivieren';
$string['enablecourserelativedates_desc'] = 'Zulassen, dass Daten im Kurs relativ zum Startdatum des\\*der Nutzers\\*in verwendet werden.';
$string['enablegravatar_help'] = 'Wenn diese Option aktiviert ist, versucht Moodle ein Profilbild von Gravatar anzuzeigen, falls Nutzer\\*innen kein eigenes Profilbild hochgeladen haben.';
$string['enableuserfeedback_desc'] = 'Wenn diese Option aktiviert ist, wird im Dashboard und in der Fußzeile der Link "Feedback geben" angezeigt, damit Nutzer\\*innen ein Feedback zur Software an das Moodle HQ geben können. Wenn die Option "Nächste Feedback-Erinnerung" aktiviert ist, wird dem\\*der Benutzer\\*in im angegebenen Intervall auch eine Erinnerung im Dashboard angezeigt. Wenn Sie "Nächste Erinnerung zum Feedback" auf "Nie" setzen, wird die Dashboard-Erinnerung deaktiviert, während der Link "Feedback zur Software geben" in der Fußzeile verbleibt.';
$string['enrolmultipleusers'] = 'Nutzer*innen einschreiben';
$string['fatalsessionautostart'] = '<p>Schwerwiegender Konfigurationsfehler - bitte benachrichtigen Sie Ihre*n Server-Administrator*in</p> <p>Um ordnungsgemäß zu arbeiten, ist für Moodle eine Änderung in den PHP-Einstellungen notwendig.<br /><code> session.auto_start=off</code> muss gesetzt sein!<br />Diese Einstellung wird auf den Server geändert, u.z. in der Datei <code>php.ini</code>, in der Apache/IIS Konfiguration oder in der Datei <code>.htaccess</code>.</p>';
$string['forceloginforprofileimage_help'] = 'Diese Option legt fest, dass Nutzer\\*innen eingeloggt sein müssen, um Profilbilder sehen zu können. Bei E-Mail-Nachrichten wird nur das Standardbild eingesetzt.';
$string['gravatardefaulturl_help'] = 'Gravatar benötigt ein Standardbild, wenn für bestimmte Nutzer\\*innen kein Profilbild gefunden werden kann. Sie haben mehrere Möglichkeiten: (1) Das Feld bleibt leer und Moodle verwendet ein vorgegebenes Bild. (2) Sie geben ein von Ihnen gewählten Bild über eine vollständige URL vor. (3) Oder Sie lassen <a href="https://en.gravatar.com/site/implement/images/#default-image">Standardbilder von Gravatar</a> erzeugen.';
$string['groupenrolmentkeypolicy_desc'] = 'Diese Option legt fest, dass für Einschreibeschlüssel zu Gruppen die gleichen Regeln gelten wie für Nutzendenkennwörter.';
$string['guestroleid_help'] = 'Diese Rolle wird Gästen automatisch zugewiesen. Sie wird außerdem vorübergehend vergeben, wenn Nutzer\\*innen über den \'Gastzugang\' einen Kurs betreten, sich dort aber nicht einschreiben.';
$string['helpadminseesall'] = 'Sollen Administrator*innen alle Kalendereinträge sehen oder nur diejenigen aus Kursen, in die sie selber eingeschrieben sind? Unabhängig von der gewählten Option können Administrator*innen die Termine für jeden Kurskalender verwalten, indem sie zuerst zum Kurs navigieren und dann direkt auf den Kurskalender zugreifen.';
$string['helpsitemaintenance'] = 'Der Wartungsmodus sperrt die Website für Arbeiten am System, für Installationen von Updates und Zusatzmodulen. Die Anmeldung ist ausschließlich für Administrator*innen möglich.';
$string['hiddenuserfields'] = 'Nutzer*innenfelder verbergen';
$string['hidefromstudents'] = 'Für Teilnehmer*innen verbergen';
$string['includemoduleuserdata'] = 'Nutzer*innendaten aus Modulen einbeziehen';
$string['langmenuinsecurelayout_desc'] = 'Wenn diese Option aktiviert ist, können Nutzer\\*innen ihre Sprache ändern, wenn sie einen Test oder eine andere Aktivität im sicheren Layout versuchen.';
$string['lockoutemailbody'] = 'Guten Tag, Ihr Konto mit dem Anmeldenamen {$a->username} wurde nach mehreren ungültigen Login-Versuchen auf dem Server \'{$a->sitename}\' gesperrt. Um das Konto sofort zu entsperren, gehen Sie auf folgende Adresse {$a->link}. In den meisten Fällen sollte dies als klickbarer Link angezeigt werden. Sollte ein Klick nicht funktionieren, kopieren Sie die Adresse in das Adressfeld Ihres Webbrowsers. Um Hilfe zu bekommen, wenden Sie sich an {$a->admin}. Ihr E-Learning-Team';
$string['lockoutthreshold_desc'] = 'Nach wie vielen erfolglosen Anmeldeversuchen soll ein Nutzendenkonto vorübergehend gesperrt werden? Mit dieser Option werden Angriffe auf Ihr System erschwert.';
$string['logguests_help'] = 'Diese Einstellung legt fest, ob die Aktionen über den Gastzugang unabhängig von den anderen Nutzendenkonten geloggt werden soll. Es wird dringend empfohlen, bei produktiven Websites diese Einstellung zu aktivieren, auch wenn zur Verringerung der Serverlast die Deaktivierung von Logdaten für den Gastzugang erwogen wird.';
$string['maxusersperpage'] = 'Maximale Nutzer*innenanzahl pro Seite';
$string['mediapluginswfnote'] = 'Sicherheitswarnung: Normale Nutzer*innen dürfen keine SWF-Flashdateien einbetten.';
$string['mnetrestore_extusers'] = '<strong>Achtung:</strong> Die Sicherungsdatei enthält externe Moodle-Nutzer*innenkonten, die bei der Wiederherstellung angelegt werden.';
$string['mnetrestore_extusers_admin'] = '<strong>Achtung: </strong>Diese Sicherungsdatei scheint von einer anderen Moodle-Instanz zu stammen und externe Nutzer*innenkonten aus dem Moodle-Netzwerk zu enthalten. Die Wiederherstellung wird versuchen, die Moodle-Netzwerk-Hosts für alle erzeugten Nutzer*innen anzupassen. Die nicht passenden Nutzer*innenkonten werden automatisch auf die interne Authentifizierung gesetzt (anstelle von MNET) und in der Logdatei festgehalten.';
$string['mnetrestore_extusers_mismatch'] = '<strong>Achtung:</strong> Die Sicherungsdatei wurde in einem anderen Moodle erzeugt und enthält externe Nutzer*innenkonten aus dem Moodle-Netzwerk, die evtl. nicht wiederhergestellt werden können. Diese Aktion wird nicht unterstützt. Nur wenn Sie sicher sind, dass die Sicherung aus diesem Moodle stammt oder dass alle Nutzer*innenkonten aus dem Moodle-Netzwerk verfügbar sind, können Sie die Wiederherstellung fortsetzen.';
$string['mnetrestore_extusers_noadmin'] = '<strong>Achtung: </strong>Diese Sicherungsdatei scheint von einer anderen Moodle-Instanz zu stammen und externe Nutzer*innenkonten aus dem Moodle-Netzwerk zu enthalten. Sie sind nicht berechtigt, diese Art von Wiederherstellung durchzuführen. Bitte nehmen Sie Kontakt mit dem*der Administrator*in Ihrer Website auf oder führen Sie alternativ die Wiederherstellung für den Kurs ohne Nutzer*inneninformationen (Module, Dateien, ...) durch.';
$string['mnetrestore_extusers_switchuserauth'] = 'Der*die externe Nutzer*in {$a->username} aus dem Moodle-Netzwerk (von {$a->mnethosturl} kommend) wechselte zum*zur lokal authentifizierten Nutzer*in {$a->auth}';
$string['moodleapp_help'] = '<p>Mit der kostenlosen Moodle-App können Nutzer\\*innen mit mobilen Endgeräten auf ihre Kurse zugreifen. Zusätzliche Funktionen der Moodle-App sind mit einem Pro oder Premium App Plan verfügbar.</p> <a href="https://moodle.com/mobile-app">Holen Sie sich die Moodle-App</a><br /> <a href="https://apps.moodle.com">Moodle Apps Portal</a>';
$string['navadduserpostslinks'] = 'Links zu Nutzer*innenbeiträgen einfügen';
$string['navadduserpostslinks_help'] = 'Bei jedem\\*r Nutzer\\*in werden zwei Links in die Navigation für Forenthemen und Diskussionsbeiträge des\\*der Nutzers\\*in auf der Startseite und in seinen Kursen eingefügt.';
$string['navsortmycourseshiddenlast_help'] = 'Diese Option legt fest, dass alle verborgenen Kurse nach den sichtbaren Kursen aufgeführt (für Nutzer\\*innen, die verborgene Kurse anzeigen können). Andernfalls werden alle Kurse unabhängig von ihrer Sichtbarkeit gemäß der Einstellung "Meine Kurse sortieren" aufgelistet.';
$string['passwordchangetokendeletion'] = 'Nutzer*innen-Token bei Kennwortänderung löschen';
$string['passwordchangetokendeletion_desc'] = 'Die Option legt fest, dass alle Nutzer\\*innen-Token für Webservice-Zugriffe bei einer Kennwortänderung gelöscht werden.';
$string['passwordreuselimit_desc'] = 'Diese Option legt fest, wie oft Nutzer\\*innen ein anderes Kennwort verwenden müssen, bevor sie ein altes Kennwort wiederbenutzen dürfen. Die Hashwerte der bisher benutzten Kennwörter werden intern gespeichert. Diese Option funktioniert nicht mit allen externen Authentifizierungen.';
$string['profileconfirmfielddeletion'] = 'Für das zu löschende Feld gibt es {$a} Nutzer*inneneinträge. <br />Möchten Sie das Feld wirklich löschen?';
$string['profilesforenrolledusersonly'] = 'Profilzugriff nur für eingetragene Nutzer*innen';
$string['profilevisibleprivate'] = 'Sichtbar für Nutzer*in';
$string['profilevisible_help'] = '\\* Nicht sichtbar - Für private Daten, nur sichtbar für Administrator\\*innen \\* Sichtbar für Nutzer\\*innen - Für private Daten, nur sichtbar für Nutzer\\*innen und Administrator\\*innen \\* Sichtbar für Nutzer\\*innen, Trainer\\*innen und Administrator\\*innen - Für private Daten, nur sichtbar für Nutzer\\*innen, Trainer\\*innen und Administrator\\*innen (im Kursprofil) \\* Sichtbar für alle - Keine privaten Daten';
$string['registrationwarningcontactadmin'] = 'Diese Website ist noch nicht registriert. Bitte benachrichtigen Sie den*die Administrator*in.';
$string['restorernewroleid'] = 'Rolle für Wiederhersteller*in in Kursen';
$string['restorernewroleid_help'] = 'Wenn ein\\*e Nutzer\\*in nicht bereits das Recht zum Verwalten des neu wiederhergestellten Kurses hat, wird die hier angegebene Rolle zugewiesen. Die Person wird u.U. dabei automatisch in den Kurs eingeschrieben. Wählen Sie \'keine\' falls bei der Wiederherstellung nicht automatisch eine Rolle im Kurs zugewiesen werden soll.';
$string['riskconfig'] = 'Nutzer*innen könnten Einstellungen für die Website und das Erscheinungsbild verändern.';
$string['riskdataloss'] = 'Nutzer*innen könnten große Mengen von Inhalten und Informationen zerstören';
$string['riskmanagetrust'] = 'Nutzer*innen könnten die Vertrauenseinstellungen anderer Nutzer*innen verändern.';
$string['riskpersonal'] = 'Nutzer*innen könnten Zugang zu persönlichen Informationen anderer Nutzer*innen erhalten.';
$string['riskspam'] = 'Nutzer*innen könnten Spam-Mails an andere Nutzer*innen oder externe Adressen senden.';
$string['riskxss'] = 'Nutzer*innen könnten Dateien und Texte einfügen, die Cross-Site-Scripting (XSS) ermöglichen.';
$string['searchallavailablecoursesdesc'] = 'Wenn die Suche nur in Kursen, in denen die Person eingeschrieben ist aktiviert ist, werden Kursinformationen (Name und Beschreibung) und Kursinhalte nur in Kursen gesucht, in denen der*die Nutzer*in eingeschrieben ist. Andernfalls werden Kursinformationen und Kursinhalte in allen Kursen gesucht, auf die der*die Nutzer*in Zugriff hat, wie z.B. Kurse mit aktiviertem Gastzugang.';
$string['searchindexwhendisabled_desc'] = 'Diese Option erlaubt dem regelmäßigen Task, den Suchindex auch bei deaktivierter Suche zu erstellen. Dies ist sinnvoll, wenn der Index erstellt werden soll, bevor die Suchfunktion den Nutzer\\*innen angezeigt wird.';
$string['sessionautostartwarning'] = '<p> Schwerwiegender Konfigurationsfehler entdeckt. Bitte Server-Administrator*in informieren.</p><p>Für eine korrekte Funktionsweise ist eine Änderung von PHP-Einstellung für Moodle erforderlich. </p><p><code>session.auto_start</code> muss auf <code>off</code> gesetzt werden.</p><p>Die Einstellung erfolgt in der <code>php.ini</code>-Datei, in der <br /> Apache/IIS Konfiguration oder der <code>.htaccess</code>-Datei auf dem Server.</p>';
$string['settingsafemode'] = 'Moodle ist nicht vollständig kompatibel mit dem Safe Mode. Bitten Sie Ihre*n Server-Administrator*in, diesen Modus auszuschalten. Rechnen Sie mit verschiedenen Problemen, falls Sie Moodle mit eingeschaltetem Safe Mode installieren.';
$string['showuseridentity'] = 'Nutzer*innenidentität anzeigen';
$string['showuseridentity_desc'] = 'Bei der Nutzendensuche und in Nutzendenlisten werden diese Felder zusätzlich zum Namen angezeigt. Die Felder sind nur sichtbar für Nutzer\\*innen mit der Berechtigung moodle/site:viewuseridentity; normalerweise sind dies Trainer\\*innen und Manager\\*innen. (Die Option ist sinnvoll, wenn eines oder mehrere der gewählten Felder in Ihrer Institution als Pflichtfelder vorhanden sind, bsp. für die Bezeichnung einer Klasse.) Mit \\* gekennzeichnete Felder sind seitenspezifische Nutzendenprofilfelder. Sie können diese Felder auswählen, aber es gibt derzeit einige Ansichten, auf denen sie nicht angezeigt werden.';
$string['sitemaintenanceon'] = 'Die Website ist momentan im Wartungsmodus. Die Anmeldung ist ausschließlich für Administrator*innen möglich.';
$string['sitemaintenancewarning'] = 'Die Website ist momentan im Wartungsmodus. Die Anmeldung ist ausschließlich für Administrator*innen möglich. <br /><a href="maintenance.php"> Wartungsmodus beenden </a>.';
$string['sitemaintenancewarning2'] = 'Die Website ist momentan im Wartungsmodus. Die Anmeldung ist ausschließlich für Administrator*innen möglich. <br /><a href="{$a}"> Wartungsmodus beenden </a>.';
$string['sitepolicyhandler_desc'] = 'Wählen Sie die Komponente aus, um die Bestätigung der Datenschutzvorgaben der Website einzuholen. Die Standardverarbeitung bietet eine einfache Funktionalität, gesteuert durch die beiden weiteren Einstellungen \'sitepolicy\' und \'sitepolicyguest\'. Die erweiterte Funktion ermöglich die Bestimmungen besser zu verwalten, die Nutzer\\*innen zu informieren, ihre Einwilligung einzuholen und die Zustimmung bei Kindern (unter 16 Jahre) zu verwalten.';
$string['statsuserthreshold'] = 'Schwelle für die Nutzer*innenzahl';
$string['suspenduser'] = 'Nutzer*innenkonto sperren';
$string['taskdeleteincompleteusers'] = 'Unvollständige Nutzer*innenprofile löschen';
$string['taskdeleteunconfirmedusers'] = 'Unbestätigte Nutzer*innenprofile löschen';
$string['tasksendnewuserpasswords'] = 'Neues Nutzer*innenkennwort senden';
$string['timezoneforced'] = 'Von Administrator*in festgelegt';
$string['timezoneisforcedto'] = 'Für alle Nutzer*innen festgelegt';
$string['tokenduration'] = 'Zeitlimit für Nutzer*innen-Token';
$string['unsuspenduser'] = 'Nutzer*innenkonto aktivieren';
$string['updateaccounts'] = 'Bestehende Nutzer*innenkonten aktualisieren';
$string['updateautocheck_desc'] = 'Wenn diese Option aktiviert ist, wird für Ihrer Website automatisch geprüft, ob für Moodle oder ein zusätzliches Plugin aktuellere Versionen verfügbar sind. Falls eine Aktualisierung vorhanden ist, werden die Administrator\\*innen benachrichtigt.';
$string['updatenotificationfooter'] = 'Ihre Website \'{$a->siteurl}\' sucht automatisch nach verfügbaren Aktualisierungen und versendet Systemnachrichten an Administrator*innen. Sie können die automatische Suche deaktivieren. Den Versand der Mitteilungen können Sie über \'Website-Administration > Server > Aktualisierungsmitteilungen\' ausschalten oder die Einstellungen im Bereich \'Meine Einstellungen\' anpassen.';
$string['upgradeforumreadinfo'] = 'Mit einer neuen Funktion in Moodle 1.5 können Forenbeiträge als gelesen/ungelesen markiert werden. Um diese Funktion zu verwenden, müssen die Datenbanktabellen aktualisiert werden. Je nach Größe der Datenbank kann dieser Vorgang längere Zeit (u.U. mehrere Stunden) erfordern. Führen Sie diesen Vorgang am besten in Zeiten mit wenigen Zugriffen aus. Die Website funktioniert während der Umstellung weiter. Die Nutzer*innen bemerken davon nichts. Wenn Sie den Vorgang einmal gestartet haben, darf er nicht unterbrochen werden. Lassen Sie das Browserfenster dabei offen. Sollten Sie das Browserfenster versehentlich schließen, können Sie den Prozess neu starten. <br />Wollen Sie nun starten?';
$string['user'] = 'Nutzer*in';
$string['userbulk'] = 'Nutzer*innenverwaltung (Bulk)';
$string['userbulkdownload'] = 'Nutzer*innen exportieren als';
$string['userdefaultpreferences'] = 'Voreingestellte Nutzer*inneneinstellungen';
$string['userfeedbackencouragement'] = '<p>Moodle verfügt über eine neue Funktion, mit der Nutzer*innen ein Feedback zur Moodle-Software abgeben können. Diese Umfrage wird über einen externen Server bereitgestellt. Für die Umfrage werden keine personenbezogenen Daten erfasst oder an den externen Server übertragen.</p> <p>Moodle HQ ist sehr um eine offene und transparente Datenerhebung bemüht. Die Administrator*innen sollen diese Funktionalität kennen und voll kontrollieren können. Das Feedback der Nutzer*innen unterstützt das Moodle HQ sehr, die Software zu verbessern. Um diese Funktion zu aktivieren, gehen Sie bitte zu <a href="{$a}">Feedback-Einstellungen</a>.</p>';
$string['userfeedbacknextreminder_desc'] = 'Wann sollen die Nutzer\\*innen erneut nach ihrem Feedback gefragt werden?';
$string['userfeedbackremindafter_desc'] = 'Nutzer\\*innen sollen nach der angegebenen Zahl von Tagen erneut um ein Feedback gebeten werden.';
$string['userfiltersdefault'] = 'Voreingestellte Nutzer*innenfilter';
$string['userfiltersdefault_desc'] = 'Wählen Sie die Filter aus, die auf der Seite "Nutzendenliste anzeigen" und auf der Seite "Nutzendenverwaltung (Bulk)" angezeigt werden sollen. Eine Mehrfachauswahl ist möglich. Die nicht ausgewählten Filter sind verfügbar, wenn Sie auf den Link "Mehr anzeigen" klicken.';
$string['userimagesdisabled'] = 'Bilder im Nutzer*innenprofil sind deaktiviert.';
$string['userlist'] = 'Nutzer*innenliste anzeigen';
$string['usermanagement'] = 'Nutzer*innenverwaltung';
$string['userpolicies'] = 'Nutzer*inneneigenschaften';
$string['userpreference'] = 'Nutzer*inneneinstellungen';
$string['userquota_desc'] = 'Das Gesamtspeichervolumen eines\\*r Nutzers\\*in für seine persönliche Dateiablage';
$string['users'] = 'Nutzer*innen';
